version: '3.8'
services:
    nginx:
        image: williansebastiao/nginx:latest
        container_name: nginx-${APP_ENV}
        ports:
            - ${APP_PORT_NGINX}:80
        volumes:
            - .:/var/www/app
        depends_on:
            - php
        networks:
            - ethos
    php:
        image: williansebastiao/php:8.1
        container_name: php-${APP_ENV}
        ports:
            - ${APP_PORT_PHP}:9000
        volumes:
            - .:/var/www/app
        networks:
            - ethos
networks:
    ethos:
        driver: bridge
